version: '3.8'

services:
  api:
    build: ./api
    ports:
      - "3000:3000"
    networks:
      adaitsnetwork:
        aliases:
          - api

  nginx:
    build: ./nginx
    ports:
      - "8080:80"
    networks:
      - adaitsnetwork

networks:
  adaitsnetwork:
    driver: bridge